.github/workflows/release.yml
=> remove "v" from version number

.github/workflows/release.yml, gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/JsonApiConverter.java
=> Fix version number

.gitignore, gridcapa-cse-valid-api/pom.xml, gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/resource/CseValidRequest.java, gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/resource/ProcessType.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/JsonApiConverterTest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/resource/CseValidRequestTest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/resource/CseValidResponseTest.java, gridcapa-cse-valid-api/src/test/resources/validRequest.json, gridcapa-cse-valid-api/target/test-classes/validRequest.json
=> add files in request

gridcapa-cse-valid-app/pom.xml
=> test for javadoc error

gridcapa-cse-valid-app/pom.xml, pom.xml
=> remove javadoc for xsd files

gridcapa-cse-valid-app/pom.xml
=> revret commit

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileExporter.java
=> fix to visualize result file in IHM

Dockerfile, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileImporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/UrlValidationService.java, gridcapa-cse-valid-spring-boot-starter/src/main/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidClient.java, gridcapa-cse-valid-spring-boot-starter/src/test/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidClientTest.java
=> Adapt starter to spring cloud stream

gridcapa-cse-valid-app/pom.xml
=> Exclude generated sources from xsd of javadoc check for release

gridcapa-cse-valid-app/pom.xml, pom.xml
=> Exclude generated sources from xsd in main POM

gridcapa-cse-valid-app/pom.xml
=> Add OLF as runtime dependency for main loadflow provider

gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/resource/CseValidRequest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/JsonApiConverterTest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/resource/CseValidRequestTest.java, gridcapa-cse-valid-api/src/test/resources/validRequest.json, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/TcDocumentTypeWriterTest.java
=> Added export corner field in the CseValidRequest

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/Constants.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidApplication.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/TTimestampWrapper.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/TcDocumentTypeWriter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/configuration/EicCodesConfiguration.java, gridcapa-cse-valid-app/src/main/resources/application.yml, gridcapa-cse-valid-app/src/main/resources/xsd/tc-document.xsd, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/TTimestampWrapperTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/TcDocumentTypeWriterTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/configuration/EicCodesConfigurationTest.java, gridcapa-cse-valid-app/src/test/resources/application.yml
=> [CSE Valid] [Export corner] TS with augmented NTC identification

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/Constants.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/exception/CseValidRequestValidatorException.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/validator/CseValidRequestValidator.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/util/CseValidRequestTestData.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/util/TimeStampTestData.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/validator/CseValidRequestValidatorTest.java
=> Use correct crac based on calculation direction

pom.xml
- task-manager : 1.13.0, 
- minio-adapter : 1.0.0,
- rao-runner : 1.11.0
=> Upgrade task-manager, minio-adapter and rao-runner

pom.xml
=> Upgrade farao-dependencies to version 1.11.0 and farao-dichotomy to version 4.9.1

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidNetworkShifter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/TTimestampWrapper.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationService.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/utils/TCalculationDirectionTestData.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/utils/TSplittingAndShiftingFactorsTestData.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/utils/TimestampTestData.java
=> Dichotomie export corner

pom.xml
=> Upgrade farao-core to version 4.2.6

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileImporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/ZonalScalableProvider.java, gridcapa-cse-valid-app/src/test/resources/com/farao_community/farao/cse_valid/app/EmptyGlsk.xml, pom.xml
=> Upgrade farao-dependencies to version 1.13.0 and use new GLSK importer

pom.xml
=> Upgrade farao-dichotomy to 4.1.0 and task-manager-api to 1.16.0

Dockerfile, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/NetPositionHelperTest.java, pom.xml
=> Upgrade dependencies

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/validator/CseValidRequestValidator.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/validator/CseValidRequestValidatorTest.java
=> Fix CRAC file required error

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/validator/CseValidRequestValidator.java
=> Fix crac file required

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/ZonalScalableProvider.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/helper/LimitingElementHelper.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoValidator.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/LimitingElementHelperTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoValidatorTest.java, pom.xml
=> Upgrade gridcapa valid

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/RaoValidator.java, gridcapa-cse-valid-app/src/main/resources/logback.xml, pom.xml
=> Improve exceptions handling and logs

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/helper/NetPositionHelper.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/NetPositionHelperTest.java
=> Change the way of computing italian import

gridcapa-cse-valid-api/pom.xml, gridcapa-cse-valid-app/pom.xml, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileExporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileImporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/TTimestampWrapper.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyNetworkValidator.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/helper/LimitingElementHelper.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationService.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/FileImporterTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/LimitingElementHelperTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationServiceTest.java, pom.xml
=> Migration from farao-core to powsybl-open-rao

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/helper/NetPositionHelper.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/NetPositionHelperTest.java
=> Undo changes on how to calculate italian import

gridcapa-cse-valid-app/src/main/resources/application.yml, gridcapa-cse-valid-app/src/test/resources/application.yml
=> Harmonize application.yml

gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/JsonApiConverter.java, gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/resource/CseValidResponse.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/JsonApiConverterTest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/resource/CseValidResponseTest.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidListener.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileExporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/configuration/AmqpMessagesConfiguration.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidListenerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/configuration/AmqpMessagesConfigurationTest.java, gridcapa-cse-valid-app/src/test/resources/application.yml, gridcapa-cse-valid-spring-boot-starter/src/main/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidClient.java, gridcapa-cse-valid-spring-boot-starter/src/main/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidResponseConversionHelper.java, gridcapa-cse-valid-spring-boot-starter/src/test/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidClientTest.java, gridcapa-cse-valid-spring-boot-starter/src/test/java/com/farao_community/farao/gridcapa_cse_valid/starter/CseValidResponseConversionHelperTest.java
This reverts commit a5658ae12869b641155c7da30373ab51ba90330d.
=> Revert "Delete response sent to cse-valid-adapter"

gridcapa-cse-valid-app/pom.xml, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileExporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/FileImporter.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationService.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/FileImporterTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationServiceTest.java, gridcapa-cse-valid-app/src/test/resources/20211125_0030_2D4_CRAC_FR1.xml, pom.xml
=> Upgrade farao dependencies to v1.33.0 

gridcapa-cse-valid-api/src/main/java/com/farao_community/farao/cse_valid/api/resource/CseValidRequest.java, gridcapa-cse-valid-api/src/test/java/com/farao_communityfarao/cse_valid/api/resource/CseValidRequestTest.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyNetworkValidator.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ComputationService.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/TcDocumentTypeWriterTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyNetworkValidatorTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/utils/CseValidRequestTestData.java, pom.xml
=> manage run id

gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyNetworkValidator.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunner.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationService.java, gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationService.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyNetworkValidatorTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/helper/LimitingElementHelperTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationServiceTest.java, pom.xml
=> Upgrade rao-runner and farao-dichotomy versions

.github/workflows/ci-commit.yml, .github/workflows/ci-master.yml, .github/workflows/release.yml, Dockerfile, pom.xml
=> Upgrade to Java 21

pom.xml
=> Upgrade to OpenRao 6.3.0

gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidHandlerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidListenerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/CseValidNetworkShifterProviderTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/dichotomy/DichotomyRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/rao/CseValidRaoRunnerTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/ExportCornerComputationServiceTest.java, gridcapa-cse-valid-app/src/test/java/com/farao_community/farao/cse_valid/app/service/FullImportComputationServiceTest.java, pom.xml
Signed-off-by: thiriondan <daniel.thirion@rte-france.com>
=> Upgrade to Spring Boot 3.4.6 & Spring Cloud 2024.0.1

gridcapa-cse-valid-app/pom.xml, gridcapa-cse-valid-spring-boot-starter/pom.xml
=> Add Maven configuration to enable inline mocking
